### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by A-Kod** [m0nkeyplay/NessusPro#1]
Hi!
Nice script, thank u!
I’m trying to use it with Nessus professional 8.8.0 and get the following error (on the photo below). 
I set npURL, put_files, ak & sk. 
![470E53D1-F71C-4BEE-A0E8-375B533A166E](https://user-images.githubusercontent.com/17290512/71355531-6e0bb200-2590-11ea-8f24-abb4c1d86056.jpeg)
Can u help me to resolve that problem, please!

**Comment by m0nkeyplay** [comment]
I can’t see the name of the scan you are looking for, but by the error it may not be there to download. I didn’t do a lot of error checking  for that in the script. 

If the name of the scan has a space, please put in it double quotes and see if that resolved the issue until I can clean up the code for better validation of names and downloads.

**Comment by A-Kod** [comment]
This is exactly how I tried. 
![1F741D1F-F6C8-4405-ADB0-BE3F19E61713](https://user-images.githubusercontent.com/17290512/71365589-84296a80-25b0-11ea-95ac-202ff3bc9add.jpeg)

**Comment by A-Kod** [comment]
This is exactly how I tried. 
![27D75D4E-87C1-4D71-A708-FA73592EB3CB](https://user-images.githubusercontent.com/17290512/71365906-690b2a80-25b1-11ea-940b-2985143397d5.jpeg)

**Comment by A-Kod** [comment]
This is exactly how I tried. 
![877CA6DD-75B7-44DE-ABCB-4A89793B40A1](https://user-images.githubusercontent.com/17290512/71365944-8b04ad00-25b1-11ea-94a6-2962709f5782.jpeg)

**Comment by A-Kod** [comment]
And in the output file there is only the information, which contains scan name, scan_id, file_id and selected format.

**Comment by m0nkeyplay** [comment]
Give a whirl with the script in the test branch and let me know that goes. I did some more name massaging to see if that helps - as well as putting in some more debugging.

**Comment by A-Kod** [comment]
It works! Thank u very much!
I just added “\” in line 204, otherwise there is a “EOL while scanning string literal“ error. 
Another question arose: why did u decide not to add HTML output?
I tried to do it, but unfortunately failed. 
The script downloads the html-file, but it is empty.

**Comment by A-Kod** [comment]
Also noticed, that the script downloads the oldest report of the scan with the specified name. But how to get the latest?

**Comment by A-Kod** [comment]
Fixed the problem with the latest report by editing the condition (on the photo below). 
![BF27E4A5-8544-46DB-803F-3D155993DA4E](https://user-images.githubusercontent.com/17290512/71415057-0f673680-266b-11ea-8d17-d31384dd08c5.jpeg)

**Comment by m0nkeyplay** [comment]
Glad it’s working for you. Thanks for the fixes. Please contribute the updates back and we can update the scripts.
