### ISSUE TITLE
Option to export as HTML?

### ISSUE THREAD

**Issue by AshDee** [m0nkeyplay/NessusPro#3]
Is there a possibility to enhance the code to export the scan as HTML file? I tried adding the file format, which works. But i would like to know how to add the chapters option to get the data in HTML file.

**Comment by m0nkeyplay** [comment]
I'll see if I can get my hands on a Pro instance and update if I can.

**Comment by AshDee** [comment]
Thank you @m0nkeyplay.
In the meantime, I used another python script to download the reports as html.
[https://github.com/tenable/nessrest](url)

I guess the only addition would be passing the chapters option for the html. because there was no option to pass chapters, html returns just the header for now

**Comment by AshDee** [comment]
Hello @m0nkeyplay ,
I have solved the issue. You can add it as an enhancement. The only requirement was to add the chapters in report_data in line 117.
```report_data = '{"filter.search_type":"or","format":"'+stype+'","chapters":"vuln_hosts_summary"}'```
The various chapters available are vuln_hosts_summary, vuln_by_host, compliance_exec, remediations, vuln_by_plugin, compliance

**Comment by AshDee** [comment]
Adding @A-Kod who also wanted html output 😃

**Comment by m0nkeyplay** [comment]
Thanks for looking up the info!  I've made the change, added html and chapters, along with the notes about the chapter types.  I don't have access to a Pro instance right now, so give it a whirl from the html branch I created and if it's not crashing, I'll merge it to main and then close the issue.

**Comment by AshDee** [comment]
Works as Expected 👍 .

**Comment by m0nkeyplay** [comment]
Great!  Merged. Thanks for the idea and help getting it set up!
