### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by fulldanad** [m0nkeyplay/NessusPro#5]
Hi,
the script ends up with the following error : 

Output will be: nessus
Please be patient while results are queued up.

Traceback (most recent call last):
  File "npScanExport.py", line 200, in <module>
    parse_json(check_url,sscan)
  File "npScanExport.py", line 193, in parse_json
    scan_history(scan_url,s_name,s_id)
  File "npScanExport.py", line 131, in scan_history
    for d in data["history"]:
TypeError: 'NoneType' object is not iterable

Any idea what it might be ?

Rgds

**Comment by m0nkeyplay** [comment]
Not being able to see your systems and test, throw this test in right before line 131.  If it catches an error we'll add it to the code so others don't need to get an error that doesn't tell us what's happening.

try:
    theHistory = data["history"]
    print("Testing for history and found some: %s"%str(theHistory))
except:
    msg = "No history found.  We can't go further without it."
    exit(msg)

**Comment by fulldanad** [comment]
I was unable to add the exept:

But the print gives the following : 

Output will be: csv
Please be patient while results are queued up.
Testing for history and found some: [{u'status': u'completed', u'uuid': u'805dc506-3d6c-3ef4-b684-6bd410bac503b546dc812d20da87', u'node_host': None, u'history_id': 1921, u'creation_date': 1643961675, u'scan_group': None, u'node_name': None, u'node_id': None, u'scheduler': 0, u'last_modification_date': 1643964338, u'alt_targets_used': False, u'schedule_type': u'manual', u'type': u'local', u'owner_id': 3}]
Testing for history and found some: [{u'status': u'completed', u'uuid': u'02a14730-38ce-ceea-39d3-f8ac5f61c40142585dfbf47f76c8', u'node_host': None, u'history_id': 1903, u'creation_date': 1643356839, u'scan_group': None, u'node_name': None, u'node_id': None, u'scheduler': 0, u'last_modification_date': 1643359793, u'alt_targets_used': False, u'schedule_type': u'manual', u'type': u'local', u'owner_id': 3}]
Testing for history and found some: [{u'status': u'completed', u'uuid': u'330f283b-158e-cdf4-ce70-c35a8c970b6317df7c405ca275ea', u'node_host': None, u'history_id': 1873, u'creation_date': 1641987443, u'scan_group': None, u'node_name': None, u'node_id': None, u'scheduler': 0, u'last_modification_date': 1641990074, u'alt_targets_used': False, u'schedule_type': u'manual', u'type': u'local', u'owner_id': 3}]
Traceback (most recent call last):
  File "npScanExport.py", line 204, in <module>
    parse_json(check_url,sscan)
  File "npScanExport.py", line 197, in parse_json
    scan_history(scan_url,s_name,s_id)
  File "npScanExport.py", line 131, in scan_history
    for d in data["history"]:
TypeError: 'NoneType' object is not iterable

**Comment by m0nkeyplay** [comment]
Let's update the except to be:

except:
    msg = "No history found. We can't go further without it."
    print(msg)
    exit()

I'm hoping to see what the 'NoneType' we are getting is.  It may be necessary to change line 131 from : for d in data["history"]: to while (d in data["history"] >= 1):

Let me know things work out.

**Comment by TacticalFajita** [comment]
I am getting a similar error.
Traceback (most recent call last):
File "npScanExport.py", line 204, in
parse_json(check_url,sscan)
File "npScanExport.py", line 197, in parse_json
scan_history(scan_url,s_name,s_id)
File "npScanExport.py", line 131, in scan_history
for d in data["history"]:
TypeError: 'NoneType' object is not iterable

I added the try/except before 131 but it didn't change anything. I did try changing Line 131 to "while (d in data["history"] >= 1):", but this causes a name error stating 'd' is not defined.

**Comment by m0nkeyplay** [comment]
Thanks for reaching out.  I don't have access to a scanner to test, so am going to ask you to try a few things so we can try to get to the bottom of it and make it work for the future.

Can you please add the following after line 129:

```
  # add me. - let's see what is being returned
  # first raw
  print(str(data))
  # then the key/value pair
  for k, v in data.items():
      print("%s --> %s")%(str(k),str(v))
  history_list = []
```

**Comment by TacticalFajita** [comment]
Thanks for the reply. I already kind of went down this route, and all of my scans show None for history. I think this is an issue with my Nessus setup rather than the script. I'm looking into what changes I need to make and can report back here for others to see.

**Comment by m0nkeyplay** [comment]
Thanks.

I made a change - adding try/except for the history, also spitting out what it sees when that doesn't work.  If it breaks the script all together please let me know so we can revert back and try something new to help out.

**Comment by m0nkeyplay** [comment]
No response and not able to test anymore, so closing this issue.
